### ISSUE TITLE
Is there a ways to set the point size?

### ISSUE THREAD

**Issue by jey3dee** [connormanning/entwine-cesium-pages#10]
Me again :). Points seem to be quite small if you zoom in and try to seem some details. Is there a way to increase the point size?

**Comment by connormanning** [comment]
Take a look at the referenced commit, which applies a [Cesium.Cesium3DTileStyle](https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileStyle.html) to set the point size.

**Comment by jey3dee** [comment]
Thank you for writing that patch. To everybody who is looking how to adapt the piont size, just add **&pointSize=x** to the get request:

`http://localhost:9000/?resource=demo&pointSize=8`
