### ISSUE TITLE
Are there ways to change point colour by height gradient?

### ISSUE THREAD

**Issue by spatialhast** [connormanning/entwine-cesium-pages#11]
Are there ways to create 'height'/'z' attribute for visualization point cloud data in Cesium with height colour gradient?
For example as in Potree:
![image](https://user-images.githubusercontent.com/3269617/33320420-d9fc23b2-d44a-11e7-805f-1429b11a75c3.png)
In Cesium3DTileStyle (https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileStyle.html#Cesium3DTileStyle) available 'color: conditions' options, but output entwine dataset not available 'Height' attribute for points. How to create this attribute?

Thanks!

**Comment by connormanning** [comment]
Closed in favor of connormanning/entwine#73.
