### ISSUE TITLE
Pointcloud doesn't show up on Cesium, although evidence suggests it should

### ISSUE THREAD

**Issue by PudgyPoppins** [connormanning/entwine-cesium-pages#14]
Hello!

I forked this project and downloaded red-rocks.laz from Entwine's website. After building and converting it for Cesium use, I served the entire directory (including this project and the Cesium-ready point cloud) over http. I loaded the project on localhost and specified the url. The Cesium map loaded, showed the Red Rocks Amphitheater, but no points.

The fact that the console outputted "Loaded tileset", and that Cesium was already centered on the amphitheater suggests that it was able to read some of the data. However, no points are visible.

I compared console outputs from localhost and cesium.entwine.io, and they're nearly identical; mine just misses the favicon (understandable, it's on localhost), and states that WebGL is "incurring lazy initalization" more often, which also shouldn't affect the pointcloud.

Console output (I've omitted the repetitions of the WebGL warning at the end):
```
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. localhost:3000
GET http://localhost:3000/favicon.ico
[HTTP/1.1 404 Not Found 0ms]

The script from “https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/?callback=loadJsonp590027&f=json” was loaded even though its MIME type (“application/json”) is not a valid JavaScript MIME type.
Loaded tileset
WebGL warning: generateMipmap: Tex image TEXTURE_2D level 0 is incurring lazy initialization.
```

Commands I ran to prepare the pointcloud:
```
entwine build -i $(pwd)/red-rocks.laz -o red-rocks_entwine -r EPSG:4978
entwine convert -i red-rocks_entwine -o red-rocks_cesium
```

**Comment by yuancaimaiyi** [comment]
@PudgyPoppins  Hi,Have you solved this problem?

**Comment by PudgyPoppins** [comment]
> @PudgyPoppins Hi,Have you solved this problem?

Wow, what a blast from the past. And I was just checking this email address on a whim, I haven't used this account in years.

Unfortunately, no, I never solved this issue lol, and if you're having the same problem after this long then I can only offer my condolences. But good luck though!

**Comment by connormanning** [comment]
You can use https://viewer.copc.io rather than this project.  The methods here are outdated - you don't need to reproject your data to 4978, and the conversion happens within the browser rather than on-disk.  Works for COPC as well as EPT data.
