### ISSUE TITLE
tileset.json isn't generated

### ISSUE THREAD

**Issue by denverpierce** [connormanning/entwine-cesium-pages#4]
Running the sample data against the sample command line on the latest entwine docker images doesn't create a /cesium folder or a tileset.json.  I tried it a few different ways, but even running against red-rocks.laz just like in the example only output standard entwine data.

**Comment by steve2007a** [comment]
Hi Denver
When I run docker with the red-rocks.laz and serve out the resulting tiles on port 9000 as instructed I can see this and other tile requests in chrome developer tools.

request: http://localhost:9000/data/red-rocks//cesium/tileset.json

So it seems to me at least that the cesium folder with the tiles and tileset.json are located at
~/entwine-cesium-pages/data/red-rocks/cesium

Does this help?
Steve

**Comment by connormanning** [comment]
Steve, I think yours is working because you are still on an older docker image - the current one isn't working right.  I've recently done a large merge and it seems to have removed Cesium capability.  I have reproduced the issue - I'll post back when I have a fix and a new docker image pushed.

**Comment by denverpierce** [comment]
That makes sense.  I tried rebuilding the image from older source, but I'm on Trusty and was having issues rebuilding.  Thanks for the response.

**Comment by connormanning** [comment]
Hello, please do a `docker pull connormanning/entwine` and try again.  Things should be back in working order.  Add a `-f` to the end of your docker run command to force a new build over the previous broken one (or just delete the `data/red-rocks` directory before running).

**Comment by denverpierce** [comment]
Works like a charm.  Am I correct that the data needs to already by scaled to uint8, but stored in las uint16 space?

**Comment by connormanning** [comment]
The scale of the input data doesn't matter - points are stored as 32-bit floats in the 3d-tile output.  Entwine uses the `POSITION`semantic for point storage since the quantized version only supports 16-bit widths (see [here](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/TileFormats/PointCloud#point-semantics)).

**Comment by denverpierce** [comment]
I wasn't clear, I was referring to the `RGB` colors, not the position.  My source data had 16bit colors, and running it un-scaled threw a PDAL error for "Unable to fetch data and convert as requested blue uint16".

**Comment by connormanning** [comment]
Ah I see.  In general, Entwine supports 16-bit colors.  However you are correct: for Cesium output the colors will need to be scaled to 8-bit values - that's the highest color resolution that the 3D-Tiles spec allows.

I don't think that the colors are required to be "stored in las uint16 space" like your question above, unless that is required by the LAS spec.  As long as all the color values fit within 8 bits, the field width in the LAS file shouldn't matter.

**Comment by aleksandrmelnyk** [comment]
Hi,

tileset.json still not generated for me. I have pulled latest connormanning/entwine and used -f at the end and there is no tileset.json under cesium folder.

thanks,

Alex.

**Comment by aleksandrmelnyk** [comment]
UPDATE: tileset.json is generated fine on ubuntu machine, but on windows 10 no tileset.json, though on both dockers pull latest one.
