### ISSUE TITLE
Input path

### ISSUE THREAD

**Issue by salutonalpha** [connormanning/entwine-cesium-pages#6]
Following this:
docker run -it -v $HOME:$HOME connormanning/entwine build /var/entwine/config/cesium.json -i https://www.liblas.org/samples/autzen/autzen-hole-utm.laz -o ~/autzen
It works.

But
If I change the input parameter like this: -i E:\\download\\pointcloud.las
It throws 
Exception in pool task: Unable to open stream for ‘E:\\download\\pointcloud.las’ with error ‘No such file or directory’
Encountered an error: Zero points found
Existing.

If I use local service supported by IIS and the URL as the input parameter like this: -i http://localhost/3DTiles/download/pointcloud.las
Performing dataset inference...
1 / 1: https://127.0.0.1/3DTiles/download/pointcloud.las
Exception in pool task: Could not read from localhost/3DTiles/download/pointcloud.las
Encountered an error: Zero points found
Existing.

**Comment by connormanning** [comment]
I don't think the `-v $HOME:$HOME` trick works on Windows, so your volume is not mapped properly.  Try `-v E:\downloads:E:\downloads` or something similar.  Docker has documentation for this [here](https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-directory-as-a-data-volume).

For your second issue, you cannot access localhost like this via docker.  I'm not positive how it works on Windows, but typically there is a magical IP address exposed within the container (called `dockerhost`) that maps to the host machine's `localhost`.  You would also need to expose the desired port, in your case 80, via your virtual machine's network management system.  Unfortunately I don't have any experience with this on Windows so I can't be of much help here.
