### ISSUE TITLE
Is there a way to keep the generated 3d-tiles on aws s3?

### ISSUE THREAD

**Issue by aleksandrmelnyk** [connormanning/entwine-cesium-pages#7]
Hi,

with greyhound we can connect to s3 and serve index from there. Are there any similar solutions for the cesium 3d-tiles? 

thanks,

Alex

**Comment by connormanning** [comment]
Cesium 3d-tiles is meant to be statically hosted, so Greyhound is not involved.  You will need to statically host your S3 bucket, which involves setting public permissions and then enabling the AWS option for static hosting.  See [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html).

**Comment by aleksandrmelnyk** [comment]
Thanks much!
