### ISSUE TITLE
Empty outputs

### ISSUE THREAD

**Issue by psawall** [connormanning/entwine-cesium-pages#8]
When running my own input data, I haven't been able to generate output points. It hasn't been throwing an error, but it ceases to process after the line 'Pushes complete - joining...'
It has worked with the red-rocks sample data, but here it creates the output folder...only it's empty.
```
$ docker run -it \
      -v $HOME:$HOME connormanning/entwine build /var/entwine/config/cesium.json \
      -i ~/entwine-cesium-pages/Input/i35_MN_LiDAR_Colored1.laz \
      -o ~/entwine-cesium-pages/Output/i35_MN_LiDAR_Colored
Performing dataset inference...
1 / 1: /c/Users/psawall/entwine-cesium-pages/Input/i35_MN_LiDAR_Colored1.laz
Transforming inference
Inferred: [(-5617.847, -9354.0843, -9355.2157), (5617.847, 9354.0843, 9355.2157)]
        File: /c/Users/psawall/entwine-cesium-pages/Input/i35_MN_LiDAR_Colored1.laz
Version:Point count hint: 304,427,611 points
Input:  Threads: 8
Output: Output path: /c/Users/psawall/entwine-cesium-pages/Output/i35_MN_LiDAR_Colored/
        Native bounds: [(-5617.847, -9354.0843, -9355.2157), (5617.847, 9354.0843, 9355.2157)]
MetadataCubic bounds: [(-9380, -9380, -9370), (9380, 9380, 9390)]
        Storing dimensions: [ile headers) -> EPSG:4978
                NumberOfReturns, ScanDirectionFlag, EdgeOfFlightLine, Classification, ScanAngleRank
                Blue, OriginIdtSourceId, GpsTime, Red, Green
        Transformation: [
                0.03888,                0.70501, 5,             0.708131,       -8.73115-1.62981e-09,
                0, 0389929,     0,      -0.707050,              1.706082,               -6.36795e+06,
        Tileset split depth: 8
Cesium: Geometric error divisor: 16

Adding 0 - /c/Users/psawall/entwine-cesium-pages/Input/i35_MN_LiDAR_Colored1.laz
 A: 0 C: 1 H: 3
        Pushes complete - joining...
```

**Comment by connormanning** [comment]
Can you upload this file somewhere so I can try to reproduce?

**Comment by psawall** [comment]
The file can be obtained here
<https://drive.google.com/open?id=0B5zr3YwgS2WbZnZnS3RXaFVQbEk>.

Thanks,

Peter

**Comment by donrv** [comment]
same issue with me too... 
Las ver: 1.2
Generating Software: lastools
https://storage.googleapis.com/geonodespatialdata/Track_A_Track_A_20161224_071052%20Profiler.zfs_10.laz

Thanks

**Comment by connormanning** [comment]
Both of the files in this thread had 16-bit color, which isn't supported by Cesium.  I've recently added the ability to truncate the colors to 8 bits using Entwine, and was successful in building your data with this config, @GeoBIMpro.  So try again with the most recent Entwine docker image using configuration file `/var/entwine/config/cesium-truncated.json` and you should be ok.

@psawall, I think your issue may be the same discussed [here](https://github.com/connormanning/entwine/issues/53) - it could be a memory issue.  Try using the 1.0 image for now - I've not yet tracked down this problem.

**Comment by connormanning** [comment]
This should be fixed now if you re-pull the docker container.
